fix: release workflow (#2673)
Co-authored-by: nichmor <nmorkotilo@gmail.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -62,11 +62,22 @@ jobs:
       - uses: actions/checkout@v4
         with:
           submodules: recursive
-      - name: Install dist
-        # we specify bash to get pipefail; it guards against the `curl` command
-        # failing. otherwise `sh` won't catch that `curl` returned non-0
-        shell: bash
-        run: "curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.25.1/cargo-dist-installer.sh | sh"
+# Turn back on when we're on the released version of dist
+#      - name: Install dist
+#        # we specify bash to get pipefail; it guards against the `curl` command
+#        # failing. otherwise `sh` won't catch that `curl` returned non-0
+#        shell: bash
+#        run: "curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.25.1/cargo-dist-installer.sh | sh"
+        # Install fork of dist to allow for binaries in the root of the tarball
+
+      # Use fork of dist to allow for binaries in the root of the tarball
+      - name: Install cargo-dist from git
+        uses: baptiste0928/cargo-install@v3
+        with:
+          crate: cargo-sort
+          git: https://github.com/ruben-arts/cargo-dist
+          branch: feature/allow_binaries_in_root_of_tar
+
       - name: Cache dist
         uses: actions/upload-artifact@v4
         with:
@@ -288,4 +299,4 @@ jobs:
           # Write and read notes from a file to avoid quoting breaking things
           echo "$ANNOUNCEMENT_BODY" > $RUNNER_TEMP/notes.txt
 
-          gh release create "${{ needs.plan.outputs.tag }}" --target "$RELEASE_COMMIT" $PRERELEASE_FLAG --title "$ANNOUNCEMENT_TITLE" --notes-file "$RUNNER_TEMP/notes.txt" artifacts/*
+          gh release create "${{ needs.plan.outputs.tag }}" --target "$RELEASE_COMMIT" $PRERELEASE_FLAG --draft true  --title "$ANNOUNCEMENT_TITLE" --notes-file "$RUNNER_TEMP/notes.txt" artifacts/*
